<?php

declare(strict_types=1);

namespace WBoost\Web\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Stage 1 of the Fabric.js v5 → v7 migration:
 *
 *  1. Promote `social_network_template_variant.canvas` from TEXT (raw JSON
 *     string) to JSONB so PostgreSQL validates payloads on insert and unlocks
 *     server-side `jsonb_set` manipulation in later stages.
 *  2. Replace the base64-data-URI `preview_image` TEXT column with a
 *     `preview_image_path` VARCHAR pointer to a Minio object. Existing
 *     previews are discarded (they regenerate on next save) — this drops
 *     ~34 MB of data URIs from the database.
 */
final class Version20260508142554 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Convert canvas to JSONB; move preview_image base64 → Minio object path.';
    }

    public function up(Schema $schema): void
    {
        // Empty canvas rows ('') are not valid JSON documents — JSONB rejects
        // them on the cast. Normalize to an empty object first.
        $this->addSql("UPDATE social_network_template_variant SET canvas = '{}' WHERE canvas = ''");

        $this->addSql('ALTER TABLE social_network_template_variant ALTER COLUMN canvas TYPE JSONB USING canvas::jsonb');
        $this->addSql('ALTER TABLE social_network_template_variant ALTER COLUMN canvas SET NOT NULL');

        // The old base64 data URIs are not migrated to Minio in this step.
        // They will be regenerated by the editor on next save; meanwhile the
        // listing falls back to `backgroundImage` (see the Twig templates).
        $this->addSql('ALTER TABLE social_network_template_variant DROP preview_image');
        $this->addSql('ALTER TABLE social_network_template_variant ADD preview_image_path VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE social_network_template_variant DROP preview_image_path');
        $this->addSql('ALTER TABLE social_network_template_variant ADD preview_image TEXT DEFAULT NULL');

        $this->addSql('ALTER TABLE social_network_template_variant ALTER COLUMN canvas DROP NOT NULL');
        $this->addSql('ALTER TABLE social_network_template_variant ALTER COLUMN canvas TYPE TEXT USING canvas::text');
        $this->addSql("UPDATE social_network_template_variant SET canvas = '' WHERE canvas = '{}'");
    }
}
