name: Tests

on:
    push:
    pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
        DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/wboost_test?serverVersion=16&charset=utf8

    services:
      db:
          image: postgres:16
          env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
          ports:
              - 5432:5432

    steps:
      -   uses: actions/checkout@v4
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: 8.3
            coverage: none # default is xdebug
            extensions: mbstring, uuid # needed by phpunit

      -   run: composer install --dev --no-progress
      -   run: bin/console importmap:install
      -   run: bin/console asset-map:compile

      -   run: vendor/bin/phpunit

  phpstan:
      runs-on: ubuntu-latest
      steps:
        -   uses: actions/checkout@v4
        -   uses: shivammathur/setup-php@v2
            with:
              php-version: 8.3
              coverage: none # default is xdebug
              extensions: mbstring, uuid # needed by phpunit

        -   run: composer install --dev --no-progress
        -   run: bin/console cache:warmup --env=dev

        -   run: composer run-script phpstan

  migrations-up-to-date:
      runs-on: ubuntu-latest
      env:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/postgres?serverVersion=16&charset=utf8

      services:
          db:
              image: postgres:16
              env:
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: postgres
              options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
              ports:
                  - 5432:5432

      steps:
          -   uses: actions/checkout@v4
          -   uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  coverage: none # default is xdebug
                  extensions: mbstring, uuid # needed by phpunit

          -   run: composer install --dev --no-progress

          -   run: bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
          -   run: bin/console doctrine:schema:update --dump-sql
          -   run: bin/console doctrine:schema:validate
